services:
  api:
    container_name: backend
    build:
      context: .
      target: build
    volumes:
      - ./:/app
      - /app/node_modules
    env_file: .env
    ports:
      - 4000:4000
    command: npm run dev
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: ${POSTGRES_HOST}
    build:
      dockerfile: ./db/Dockerfile
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - database-v:/var/lib/postgresql/database
    command: "-p ${POSTGRES_PORT}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -p ${POSTGRES_PORT} -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
        ]
      start_period: 0s
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  server-v-node-modules:
    name: "server-v-node-modules"
  database-v:
    name: "database-v"
